routes/web.php
<?php

use App\Http\Controllers\Admin\CategoriesController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\SubcategoriesController;
use App\Http\Controllers\Admin\AddmemberController;
use App\Http\Controllers\Admin\EventController;
use App\Http\Controllers\Admin\NewsController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\ImportExportController;
use App\Http\Controllers\MomentController;
use App\Http\Controllers\BusinessController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\CommitteeController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ResetPasswordController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Artisan;
use League\Flysystem\Config;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('clear-cache', function() {
    Artisan::call('optimize');
    Artisan::call('config:cache');
    Artisan::call('route:cache');
    Artisan::call('view:clear');
    Artisan::call('cache:clear');
    return 'cleared';
});

// Route::get('/', function () {
//     return view('auth.login');
// });
Route::get('/', [DashboardController::class,'index'] )->middleware('auth');;

Route::get('login', function () {
    return view('auth.login');
});
Route::get('/forgot-password', [ForgotPasswordController::class, 'forgotPassword']);
Route::post('/send-reset-password-link', [ForgotPasswordController::class, 'sendResetPassWordLink']);

Route::get('/reset-password/{token}', [ResetPasswordController::class,'getPassword']);
Route::post('/reset-password', [ResetPasswordController::class, 'updatePassword']);


Auth::routes();
Route::get('logout', [LoginController::class, 'logout'])->name('get_logout');
Route::group(['middleware' =>  ['auth', 'admin']], function() {
    Route::prefix('/dashboard')->group(function () {
        Route::get('/', [DashboardController::class,'index'])->name('admin_dashboard');
        // Route::get('dashboard', [DashboardController::class,'index'])->name('admin_dashboard'); 
        Route::resource('users', UserController::class);
        Route::get('remove_user/{id}', [UserController::class, 'remove_user']);  
        Route::get('user/{id}', [UserController::class, 'edit']);  
        Route::get('create_user', [UserController::class, 'create_user'])->name('create_user'); 
        Route::resource('categories', CategoriesController::class);
        Route::get('remove_categories/{id}', [CategoriesController::class, 'remove_categories'])->name('remove_categories');
        Route::resource('subcategories', SubcategoriesController::class);
        Route::get('show_image/{id}', [SubcategoriesController::class, 'show_image']);
        Route::get('remove_subcategories/{id}', [SubcategoriesController::class, 'remove_subcategories'])->name('remove_subcategories');
        Route::get('add_family/{id}', [AddmemberController::class,'index']);
        Route::post('add_family/{id}', [AddmemberController::class, 'add_family'])->name('add_family');
        
        // Route::get('view_family',[AddmemberController::class, 'showMembers']);
        Route::get('view_family/{id}', [AddmemberController::class,'view_family'])->name('view_family');
        Route::get('remove_member/{id}', [AddmemberController::class,'remove_member']);
        Route::get('member_edit/{id}', [AddmemberController::class,'member_edit'])->name('member_edit');
        Route::put('member_update/{id}', [AddmemberController::class,'member_update'])->name('member_update');
        Route::get('memberedit/{id}',[AddmemberController::class,'MemberEdit']);
        Route::get('member/delete/{id}',[AddmemberController::class,'destroy']);
        Route::resource('news', NewsController::class);
        Route::get('news/delete/{id}',[NewsController::class,'destroy']);
        Route::get('newsList', [NewsController::class, 'newsList'])->name('newsList');
        Route::get('news_remove/{id}', [NewsController::class, 'news_remove'])->name('news_remove');
        Route::get('news_image/{id}', [NewsController::class, 'News_image']);
        Route::resource('event',EventController::class);
        Route::get('event/delete/{id}',[EventController::class, 'destroy']);
        Route::get('remove_event/{id}',[EventController::class, 'remove_event']);
        Route::get('events', [EventController::class, 'event_list'])->name('event_list');
        
        
        Route::get('export-users-csv',[ImportExportController::class, 'exportUsersCSV']);
        Route::get('export-users-pdf',[ImportExportController::class, 'exportUsersPDF']);
        Route::get('export-users-excel',[ImportExportController::class, 'exportUsersExcel']);
        Route::resource('moments',MomentController::class);
        Route::get('moments/delete/{id}',[MomentController::class,'destroy']);
        Route::resource('business',BusinessController::class);
        Route::get('business/delete/{id}',[BusinessController::class,'destroy']);

        Route::get('update-profile/{id}',[UserController::class, 'editProfile']);
        Route::get('memberadd/{id}',[AddmemberController::class, 'memberadd']) ;
        Route::get('editmember/{id}',[AddmemberController::class, 'editmemberapi']);
        // Route::get('update-user/{id}',[UserController::class, 'updateProfile']);
        // dahboard/update-user
        Route::get('categories/delete/{id}',[CategoriesController::class,'destroy']);
        Route::get('subcategories/delete/{id}',[SubcategoriesController::class,'destroy']);
        Route::get('fetchsubcategory/{id}',[CategoriesController::class,'findsubcategory']);
        Route::get('fetchOldsubCategory/{id}',[CategoriesController::class,'findOldsubCategory']);
        Route::get('fetch-category-for-subcategory/{id}',[CategoriesController::class,'findCategoryforSubcategory']);
        Route::get('fetch-business-for-category/{id}',[CategoriesController::class,'findBusinessforCategory']);
        Route::resource('committee',CommitteeController::class);
        Route::get('fetch_users/{id}',[UserController::class,'edit']);
        Route::get('fetchOldCategory-forOldsubcategory/{id}',[SubcategoriesController::class,'findOldcategoryForsubcategory']);
        Route::get('fetchOldbusiness-forOldcategory/{id}',[SubcategoriesController::class,'findOldbusinessForcategory']);
        Route::get('admin/profile',[UserController::class,'admin']);
        Route::put('updateAdminprofile',[UserController::class,'updateProfileofAdmin']);
    });
    
    
});

Route::group(['middleware' =>  ['auth', 'user']], function() {
    Route::get('user_dashboard', [DashboardController::class,'index'])->name('user_dashboard');
    
});

Route::get('test', [TestController::class,'index']);

app/Models/Committee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Committee extends Model
{
    use HasFactory;
    protected $table = 'committees';
    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['image'];
}

app/Http/Controllers/CommitteeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Committee;
use File;

class CommitteeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $committee = Committee::get();
      
        return view('admin.committee.index',compact('committee'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'image' => 'required|mimes:jpeg,png,jpg|max:3072',
        ]);
        $path = 'users/committee';
        $committee = new Committee();
        $imageName = time().'.'.$request->image->extension();  
        $request->image->move(public_path($path), $imageName);

        $committee->image = $path.'/'.$imageName;
        $committee->save();
        return back()->with('success','Committee Saved.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $committee = Committee::where('id',$id)->first();
        File::delete(public_path($committee->image));
        $committee->delete();
        return back()->with('success','Committee Deleted.');
    }
}

app/Http/Controllers/api/CommitteeController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Committee;
class CommitteeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $committee = Committee::first();
        //dd($committee);
        $image = $committee->image;
        return response()->json(['status' =>  200,'image' => $image]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/committee/index.blade.php
@extends('admin.layout.app')
@section('title', 'Committee')

@section('content')

<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="pe-7s-albums icon-gradient bg-mean-fruit"></i>
                </div>
                <div>Committee
                </div>
            </div>
        </div>
    </div>

    <div class="tabs-animation">
        <div class="mb-3 card">
            @if(session()->has('success'))
                <div class="alert alert-success alert-dismissible fade show">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ session()->get('success') }}
                </div>
            @endif
            @if ($errors->any())
                @foreach ($errors->all() as $error)
                    <div class="alert alert-danger alert-dismissible fade show">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        {{ $error }}
                    </div>
                @endforeach
            @endif
            @if(count($committee) <= 0)
            <div class="card-header-tab card-header">
                <div class="col-md-2">
                <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                    <i class="header-icon lnr-charts icon-gradient bg-happy-green"> </i>Add Committee
                </div>
                </div>
            </div>
            <div class="p-3 d-block card-body">
                <form action="/dashboard/committee" method="post" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class="col-md-12">
                        <input type="file" name="image" class="dropify">
                    </div>
                </div>
                <div class="mt-2 text-center row">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-success"><i class="pe-7s-cloud-upload"></i>Save</button>
                        <a class="btn btn-danger" href="/dashboard/committee">Cancel</a>
                    </div>
                </div>
            </form>
            </div>
            @endif
        </div>
    </div>
    <div class="tabs-animation">
        <div class="mb-3 card">
            <div class="card-header-tab card-header">
                <div class="col-md-2">
                <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                    <i class="header-icon lnr-charts icon-gradient bg-happy-green"> </i> Committee
                </div>
                </div>
            </div>
            <div class="p-3 d-block card-body">
                <div class="row">
                    <div class="col-md-12">
                        <table id="momentsTable" class="table table-bordered table-hover" style="width:100%">
                            <thead>
                                <tr>
                                    <th class="text-center border-top-0" width="5%">S.N</th>
                                    <th class="text-center border-top-0" width="10%">Image</th>
                                    <th class="text-center border-top-0" width="10%">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($committee as $comm)
                                    <tr>
                                        <td class="text-center">{{$loop->index+1}} </td>
                                        <td class="text-center">
                                            <img src="{{asset($comm->image)}}" class="img-thumbnail img-responsive">
                                        </td>
                                        <td class="text-center dropdown">
                                            <button class="btn btn-success" type="button" data-toggle="dropdown"><i class="fa fa-ellipsis-v"></i> </button> 
                                            <div class="text-center dropdown-menu" style="min-width:75px">
                                                <form action="{{ route('committee.destroy', $comm->id) }}" method="POST">
                                                    @method('DELETE')
                                                    @csrf
                                                    <button class="btn btn-danger"> <i class="fa fa-trash-o"></i> Delete</button>
                                                </form>
                                            </div>    
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@push('js')
<script>
    $('.dropify').dropify();
</script>
@endpush